# Generated by Django 5.2 on 2025-05-04 22:45

import django.db.models.deletion
import processo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Atribuicao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        max_length=200,
                        unique=True,
                        verbose_name="Nome da Área de Atribuição",
                    ),
                ),
            ],
            options={
                "verbose_name": "Área de Atribuição",
                "verbose_name_plural": "Áreas de Atribuição",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100, verbose_name="Nome")),
                ("valor", models.IntegerField(unique=True, verbose_name="Valor")),
            ],
            options={
                "verbose_name": "Categoria",
                "verbose_name_plural": "Categorias",
                "ordering": ["valor"],
            },
        ),
        migrations.CreateModel(
            name="GrupoAuditor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100, unique=True)),
                ("descricao", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Grupo de Auditores",
                "verbose_name_plural": "Grupos de Auditores",
            },
        ),
        migrations.CreateModel(
            name="Situacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=250, verbose_name="Nome")),
            ],
            options={
                "verbose_name": "Situação",
                "verbose_name_plural": "Situações",
            },
        ),
        migrations.CreateModel(
            name="TipoDemanda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Tipo de Demanda",
                "verbose_name_plural": "Tipos de Demanda",
            },
        ),
        migrations.CreateModel(
            name="TipoProcesso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=250, verbose_name="Nome")),
            ],
            options={
                "verbose_name": "Tipo de processo",
                "verbose_name_plural": "Tipos de processos",
            },
        ),
        migrations.CreateModel(
            name="TipoReuniao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Tipo de Reunião",
                "verbose_name_plural": "Tipos de Reunião",
            },
        ),
        migrations.CreateModel(
            name="Unidade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=250, verbose_name="Nome")),
            ],
            options={
                "verbose_name": "Unidade",
                "verbose_name_plural": "Unidades",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="Auditor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100, verbose_name="Nome")),
                (
                    "telefone",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Telefone"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="Email"
                    ),
                ),
                (
                    "grupo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="auditores",
                        to="processo.grupoauditor",
                        verbose_name="Grupo de Auditores",
                    ),
                ),
            ],
            options={
                "verbose_name": "Auditor",
                "verbose_name_plural": "Auditores",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="Processo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("processo", "Processo"),
                            ("demanda", "Demanda"),
                            ("acordao", "Acordão"),
                            ("relatorio_auditoria", "Relatório de Auditoria"),
                            ("recomendacao", "Recomendação"),
                            ("acao", "Ação"),
                            ("determinacao", "Determinação"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "identificador",
                    models.CharField(editable=False, max_length=10, unique=True),
                ),
                ("assunto", models.CharField(max_length=200)),
                (
                    "prioridade",
                    models.CharField(
                        choices=[
                            ("normal", "Normal"),
                            ("alta", "Alta"),
                            ("urgente", "Urgente"),
                        ],
                        default="normal",
                        max_length=10,
                    ),
                ),
                ("numero_sei", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "orgao_demandante",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("TCU", "TCU"),
                            ("CGU", "CGU"),
                            ("AUDGER", "AUDGER"),
                            ("MD", "Ministério da Defesa"),
                            ("OUTROS", "Outros"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "numero_processo_externo",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "ano_solicitacao",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[processo.models.validate_year],
                    ),
                ),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                ("data_atualizacao", models.DateTimeField(auto_now=True)),
                ("correlacao_lar", models.BooleanField(default=False)),
                ("tag", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "descricao",
                    models.TextField(blank=True, max_length=200000, null=True),
                ),
                (
                    "observacao",
                    models.TextField(blank=True, max_length=5000, null=True),
                ),
                (
                    "prazo",
                    models.DateField(blank=True, null=True, verbose_name="Prazo"),
                ),
                (
                    "data_resposta",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data da Resposta"
                    ),
                ),
                (
                    "numero_sei_resposta",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Número SEI da Resposta",
                    ),
                ),
                (
                    "data_envio_resposta",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data do Envio da Resposta"
                    ),
                ),
                (
                    "reiterado",
                    models.CharField(
                        choices=[("sim", "Sim"), ("nao", "Não")],
                        default="nao",
                        max_length=3,
                        verbose_name="Reiterado",
                    ),
                ),
                (
                    "data_reiteracao",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data da Reiteração"
                    ),
                ),
                (
                    "identificacao_achados",
                    models.TextField(
                        blank=True, null=True, verbose_name="Identificação dos Achados"
                    ),
                ),
                (
                    "documento_resposta",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Documento de Resposta",
                    ),
                ),
                (
                    "prazo_inicial",
                    models.DateField(
                        blank=True, null=True, verbose_name="Prazo Inicial"
                    ),
                ),
                (
                    "local_execucao",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Local da Execução",
                    ),
                ),
                (
                    "duracao_execucao",
                    models.DurationField(
                        blank=True, null=True, verbose_name="Duração da Execução"
                    ),
                ),
                (
                    "forma_execucao",
                    models.TextField(
                        blank=True, null=True, verbose_name="Forma de Execução"
                    ),
                ),
                (
                    "resultado_pretendido",
                    models.TextField(
                        blank=True, null=True, verbose_name="Resultado Pretendido"
                    ),
                ),
                (
                    "achados",
                    models.TextField(blank=True, null=True, verbose_name="Achados"),
                ),
                (
                    "solicitacao_prorrogacao",
                    models.BooleanField(
                        default=False, verbose_name="Solicitação de Prorrogação"
                    ),
                ),
                (
                    "atribuicao",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="processos_atribuidos",
                        to="processo.atribuicao",
                        verbose_name="Área de Atribuição",
                    ),
                ),
                (
                    "auditores_responsaveis",
                    models.ManyToManyField(
                        blank=True,
                        related_name="processos_responsavel",
                        to="processo.auditor",
                    ),
                ),
                (
                    "categoria",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="processos",
                        to="processo.categoria",
                    ),
                ),
                (
                    "pai",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subprocessos",
                        to="processo.processo",
                    ),
                ),
                (
                    "situacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="processos",
                        to="processo.situacao",
                    ),
                ),
                (
                    "tipo_demanda",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="demandas",
                        to="processo.tipodemanda",
                        verbose_name="Tipo de Demanda",
                    ),
                ),
                (
                    "tipo_processo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="processos",
                        to="processo.tipoprocesso",
                    ),
                ),
                (
                    "area_demandada",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="acoes",
                        to="processo.unidade",
                        verbose_name="Área Demandada",
                    ),
                ),
                (
                    "unidade_auditada",
                    models.ManyToManyField(
                        blank=True,
                        related_name="processos",
                        to="processo.unidade",
                        verbose_name="Unidades Auditadas",
                    ),
                ),
            ],
            options={
                "verbose_name": "Processo",
                "verbose_name_plural": "Processos",
                "ordering": ["-data_criacao"],
            },
        ),
        migrations.CreateModel(
            name="Reuniao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateTimeField(verbose_name="Data")),
                (
                    "participantes",
                    models.TextField(
                        blank=True,
                        help_text="Liste os nomes dos participantes, um por linha ou separados por vírgula.",
                        verbose_name="Participantes",
                    ),
                ),
                ("pauta", models.TextField(verbose_name="Pauta")),
                (
                    "resultado",
                    models.TextField(blank=True, null=True, verbose_name="Resultado"),
                ),
                (
                    "processo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reunioes",
                        to="processo.processo",
                        verbose_name="Processo",
                    ),
                ),
                (
                    "tipo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="processo.tiporeuniao",
                        verbose_name="Tipo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reunião",
                "verbose_name_plural": "Reuniões",
                "ordering": ["tipo"],
            },
        ),
    ]
