# Generated by Django 5.2 on 2025-04-26 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("processo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="processo",
            name="solicitacao_prorrogacao",
            field=models.BooleanField(
                default=False, verbose_name="Solicitação de Prorrogação"
            ),
        ),
    ]
