# Generated by Django 5.2 on 2025-06-08 15:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("processo", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OrgaoDemandante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name": "Órgão Demandante",
                "verbose_name_plural": "Órgãos Demandantes",
            },
        ),
        migrations.CreateModel(
            name="Prioridade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=30, unique=True)),
            ],
            options={
                "verbose_name": "Prioridade",
                "verbose_name_plural": "Prioridades",
            },
        ),
        migrations.CreateModel(
            name="Tipo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name": "Tipo de Processo",
                "verbose_name_plural": "Tipos de Processo",
                "ordering": ["nome"],
            },
        ),
        migrations.RemoveField(
            model_name="processo",
            name="tipo_processo",
        ),
        migrations.AlterModelOptions(
            name="atribuicao",
            options={
                "verbose_name": "Área de Atribuição",
                "verbose_name_plural": "Áreas de Atribuição",
            },
        ),
        migrations.AlterModelOptions(
            name="categoria",
            options={
                "ordering": ["nome"],
                "verbose_name": "Categoria",
                "verbose_name_plural": "Categorias",
            },
        ),
        migrations.AlterModelOptions(
            name="processo",
            options={
                "ordering": ["-data_cadastro"],
                "verbose_name": "Processo",
                "verbose_name_plural": "Processos",
            },
        ),
        migrations.AlterModelOptions(
            name="unidade",
            options={
                "verbose_name": "Unidade (Auditada/Demandada)",
                "verbose_name_plural": "Unidades (Auditadas/Demandadas)",
            },
        ),
        migrations.RenameField(
            model_name="processo",
            old_name="data_criacao",
            new_name="data_cadastro",
        ),
        migrations.RemoveField(
            model_name="auditor",
            name="email",
        ),
        migrations.RemoveField(
            model_name="auditor",
            name="telefone",
        ),
        migrations.RemoveField(
            model_name="categoria",
            name="valor",
        ),
        migrations.RemoveField(
            model_name="processo",
            name="achados",
        ),
        migrations.RemoveField(
            model_name="processo",
            name="data_envio_resposta",
        ),
        migrations.RemoveField(
            model_name="processo",
            name="data_reiteracao",
        ),
        migrations.RemoveField(
            model_name="processo",
            name="data_resposta",
        ),
        migrations.RemoveField(
            model_name="processo",
            name="documento_resposta",
        ),
        migrations.RemoveField(
            model_name="processo",
            name="duracao_execucao",
        ),
        migrations.RemoveField(
            model_name="processo",
            name="forma_execucao",
        ),
        migrations.RemoveField(
            model_name="processo",
            name="identificador",
        ),
        migrations.RemoveField(
            model_name="processo",
            name="local_execucao",
        ),
        migrations.RemoveField(
            model_name="processo",
            name="numero_sei_resposta",
        ),
        migrations.RemoveField(
            model_name="processo",
            name="prazo",
        ),
        migrations.RemoveField(
            model_name="processo",
            name="prazo_inicial",
        ),
        migrations.RemoveField(
            model_name="processo",
            name="reiterado",
        ),
        migrations.RemoveField(
            model_name="processo",
            name="resultado_pretendido",
        ),
        migrations.RemoveField(
            model_name="processo",
            name="solicitacao_prorrogacao",
        ),
        migrations.RemoveField(
            model_name="processo",
            name="tag",
        ),
        migrations.RemoveField(
            model_name="processo",
            name="unidade_auditada",
        ),
        migrations.AddField(
            model_name="processo",
            name="data_documento_sei",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="processo",
            name="numero",
            field=models.CharField(
                default=django.utils.timezone.now,
                editable=False,
                max_length=20,
                unique=True,
                verbose_name="Identificador",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="processo",
            name="unidades_auditadas",
            field=models.ManyToManyField(
                blank=True, to="processo.unidade", verbose_name="Unidades Auditadas"
            ),
        ),
        migrations.AlterField(
            model_name="auditor",
            name="grupo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="auditores",
                to="processo.grupoauditor",
            ),
        ),
        migrations.AlterField(
            model_name="categoria",
            name="nome",
            field=models.CharField(max_length=100, unique=True, verbose_name="Nome"),
        ),
        migrations.AlterField(
            model_name="processo",
            name="area_demandada",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="processos_demandados",
                to="processo.unidade",
                verbose_name="Área Téc. Demandada",
            ),
        ),
        migrations.AlterField(
            model_name="processo",
            name="assunto",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="processo",
            name="atribuicao",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="processo.atribuicao",
                verbose_name="Atribuído para",
            ),
        ),
        migrations.AlterField(
            model_name="processo",
            name="auditores_responsaveis",
            field=models.ManyToManyField(
                blank=True, to="processo.auditor", verbose_name="Auditores Responsáveis"
            ),
        ),
        migrations.AlterField(
            model_name="processo",
            name="categoria",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="processo.categoria",
            ),
        ),
        migrations.AlterField(
            model_name="processo",
            name="correlacao_lar",
            field=models.BooleanField(
                default=False, verbose_name="Correlação Assunto LAR"
            ),
        ),
        migrations.AlterField(
            model_name="processo",
            name="descricao",
            field=models.TextField(
                blank=True,
                help_text="Usado para Acordão, Relatório, Recomendação, Determinação, Ação.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="processo",
            name="identificacao_achados",
            field=models.TextField(
                blank=True,
                help_text="Usado para Recomendação e Determinação.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="processo",
            name="observacao",
            field=models.TextField(
                blank=True,
                help_text="Observações gerais para qualquer tipo.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="processo",
            name="pai",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="filhos",
                to="processo.processo",
                verbose_name="Processo Pai",
            ),
        ),
        migrations.AlterField(
            model_name="processo",
            name="situacao",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="processo.situacao",
                verbose_name="Situação",
            ),
        ),
        migrations.AlterField(
            model_name="processo",
            name="tipo_demanda",
            field=models.ForeignKey(
                blank=True,
                help_text="Específico para o tipo 'Demanda'.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="processo.tipodemanda",
            ),
        ),
        migrations.AlterField(
            model_name="situacao",
            name="nome",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="tipodemanda",
            name="nome",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="unidade",
            name="nome",
            field=models.CharField(
                max_length=250, unique=True, verbose_name="Nome da Unidade"
            ),
        ),
        migrations.CreateModel(
            name="Execucao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "local_acao",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Local da Ação",
                    ),
                ),
                (
                    "forma_execucao",
                    models.TextField(
                        blank=True, null=True, verbose_name="Forma de Execução"
                    ),
                ),
                (
                    "duracao_execucao",
                    models.DurationField(
                        blank=True, null=True, verbose_name="Duração da Execução"
                    ),
                ),
                (
                    "resultado_pretendido",
                    models.TextField(
                        blank=True, null=True, verbose_name="Resultado Pretendido"
                    ),
                ),
                (
                    "processo",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="execucao",
                        to="processo.processo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HistoricoProcesso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateTimeField(auto_now_add=True)),
                ("observacao", models.TextField(blank=True, null=True)),
                (
                    "alterado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "processo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historicos",
                        to="processo.processo",
                    ),
                ),
                (
                    "situacao_anterior",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="processo.situacao",
                    ),
                ),
                (
                    "situacao_nova",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="processo.situacao",
                    ),
                ),
            ],
            options={
                "verbose_name": "Histórico do Processo",
                "verbose_name_plural": "Históricos de Processos",
                "ordering": ["-data"],
            },
        ),
        migrations.AlterField(
            model_name="processo",
            name="orgao_demandante",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="processo.orgaodemandante",
                verbose_name="Órgão Demandante",
            ),
        ),
        migrations.AlterField(
            model_name="processo",
            name="prioridade",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="processo.prioridade",
                verbose_name="Prioridade",
            ),
        ),
        migrations.CreateModel(
            name="Resposta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "prazo_inicial",
                    models.DateField(
                        blank=True,
                        help_text="Prazo para Demanda, Recomendação, Determinação, Ação",
                        null=True,
                    ),
                ),
                (
                    "documento_resposta",
                    models.CharField(
                        blank=True,
                        help_text="Usado para Demanda",
                        max_length=50,
                        null=True,
                        verbose_name="Número do Documento de Resposta",
                    ),
                ),
                (
                    "solicitacao_prorrogacao",
                    models.BooleanField(
                        default=False,
                        help_text="Para Demanda, Recomendação, Determinação",
                        verbose_name="Solicitação de Prorrogação",
                    ),
                ),
                (
                    "processo",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resposta",
                        to="processo.processo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HierarquiaProcesso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_filho",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pais_permitidos",
                        to="processo.tipo",
                    ),
                ),
                (
                    "tipo_pai",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="filhos_permitidos",
                        to="processo.tipo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hierarquia de Processo",
                "verbose_name_plural": "Hierarquias de Processos",
                "unique_together": {("tipo_pai", "tipo_filho")},
            },
        ),
        migrations.AlterField(
            model_name="processo",
            name="tipo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="processo.tipo",
                verbose_name="Tipo",
            ),
        ),
        migrations.DeleteModel(
            name="Reuniao",
        ),
        migrations.DeleteModel(
            name="TipoReuniao",
        ),
        migrations.DeleteModel(
            name="TipoProcesso",
        ),
    ]
