# Generated by Django 5.2 on 2025-06-08 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("processo", "0002_orgaodemandante_prioridade_tipo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="processo",
            name="documento_sei",
            field=models.CharField(
                blank=True,
                help_text="Para Acordãos e Relatórios",
                max_length=50,
                null=True,
                verbose_name="Documento SEI (específico)",
            ),
        ),
    ]
