# Generated by Django 5.2 on 2025-06-08 17:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("processo", "0003_processo_documento_sei"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicoprocesso",
            options={
                "ordering": ["-data"],
                "verbose_name": "Histórico do Processo",
                "verbose_name_plural": "Históricos dos Processos",
            },
        ),
        migrations.RemoveField(
            model_name="historicoprocesso",
            name="observacao",
        ),
        migrations.RemoveField(
            model_name="historicoprocesso",
            name="situacao_anterior",
        ),
        migrations.RemoveField(
            model_name="historicoprocesso",
            name="situacao_nova",
        ),
        migrations.AddField(
            model_name="historicoprocesso",
            name="alteracoes",
            field=models.JSONField(
                default=dict, editable=False, verbose_name="Alterações Detalhadas"
            ),
        ),
        migrations.AddField(
            model_name="historicoprocesso",
            name="observacao_geral",
            field=models.TextField(
                blank=True,
                help_text="Observação manual sobre a mudança, se necessário.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicoprocesso",
            name="tipo_alteracao",
            field=models.CharField(
                choices=[("CRIACAO", "Criação"), ("ATUALIZACAO", "Atualização")],
                default="ATUALIZACAO",
                editable=False,
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="historicoprocesso",
            name="alterado_por",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="historicoprocesso",
            name="data",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False
            ),
        ),
    ]
