# Generated by Django 5.2 on 2025-04-09 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("valor", models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Grupo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100, unique=True)),
                ("descricao", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Situacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="TipoProcesso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="TipoReuniao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("apresentacao", "Apresentação"),
                            ("alinhamento_interno", "Alinhamento Interno"),
                            ("alinhamento_externo", "Alinhamento Externo"),
                            ("busca_solucoes", "Busca Conjunta de Soluções"),
                            ("encerramento", "Encerramento"),
                        ],
                        max_length=30,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Unidade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("sigla", models.CharField(max_length=20, unique=True)),
                ("descricao", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Auditor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("telefone", models.CharField(blank=True, max_length=20, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "grupo",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="auditores",
                        to="processos.grupo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Processo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "identificador",
                    models.CharField(editable=False, max_length=10, unique=True),
                ),
                ("assunto", models.CharField(max_length=200)),
                (
                    "prioridade",
                    models.CharField(
                        choices=[
                            ("normal", "Normal"),
                            ("alta", "Alta"),
                            ("urgente", "Urgente"),
                        ],
                        default="normal",
                        max_length=10,
                    ),
                ),
                ("numero_sei", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "orgao_demandante",
                    models.CharField(
                        choices=[
                            ("TCU", "TCU"),
                            ("CGU", "CGU"),
                            ("AUDGER", "AUDGER"),
                            ("MD", "Ministério da Defesa"),
                            ("OUTROS", "Outros"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "numero_processo_externo",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("ano_solicitacao", models.IntegerField()),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                ("data_atualizacao", models.DateTimeField(auto_now=True)),
                ("correlacao_lar", models.BooleanField(default=False)),
                ("tag", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "descricao",
                    models.TextField(blank=True, max_length=200000, null=True),
                ),
                (
                    "observacao",
                    models.TextField(blank=True, max_length=5000, null=True),
                ),
                (
                    "atribuicao",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="processos_atribuidos",
                        to="processos.grupo",
                    ),
                ),
                (
                    "auditores_responsaveis",
                    models.ManyToManyField(
                        blank=True,
                        related_name="processos_responsavel",
                        to="processos.auditor",
                    ),
                ),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="processos",
                        to="processos.categoria",
                    ),
                ),
                (
                    "situacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="processos",
                        to="processos.situacao",
                    ),
                ),
                (
                    "tipo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="processos",
                        to="processos.tipoprocesso",
                    ),
                ),
                (
                    "unidade_auditada",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="processos",
                        to="processos.unidade",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Reuniao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateTimeField()),
                ("pauta", models.TextField()),
                ("resultado", models.TextField(blank=True, null=True)),
                (
                    "participantes",
                    models.ManyToManyField(
                        related_name="reunioes", to="processos.auditor"
                    ),
                ),
                (
                    "processo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reunioes",
                        to="processos.processo",
                    ),
                ),
                (
                    "tipo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="processos.tiporeuniao",
                    ),
                ),
            ],
        ),
    ]
