# Generated by Django 5.2 on 2025-04-09 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("processos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Atribuicao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        max_length=200,
                        unique=True,
                        verbose_name="Nome da Área de Atribuição",
                    ),
                ),
            ],
            options={
                "verbose_name": "Área de Atribuição",
                "verbose_name_plural": "Áreas de Atribuição",
                "ordering": ["nome"],
            },
        ),
        migrations.RenameModel(
            old_name="Grupo",
            new_name="GrupoAuditor",
        ),
        migrations.AlterModelOptions(
            name="auditor",
            options={
                "ordering": ["nome"],
                "verbose_name": "Auditor",
                "verbose_name_plural": "Auditores",
            },
        ),
        migrations.AlterModelOptions(
            name="categoria",
            options={
                "ordering": ["valor"],
                "verbose_name": "Categoria",
                "verbose_name_plural": "Categorias",
            },
        ),
        migrations.AlterModelOptions(
            name="grupoauditor",
            options={
                "verbose_name": "Grupo de Auditores",
                "verbose_name_plural": "Grupos de Auditores",
            },
        ),
        migrations.AlterModelOptions(
            name="reuniao",
            options={
                "ordering": ["-data", "processo"],
                "verbose_name": "Reunião",
                "verbose_name_plural": "Reuniões",
            },
        ),
        migrations.AlterModelOptions(
            name="situacao",
            options={"verbose_name": "Situação", "verbose_name_plural": "Situações"},
        ),
        migrations.AlterModelOptions(
            name="tipoprocesso",
            options={
                "verbose_name": "Tipo de processo",
                "verbose_name_plural": "Tipos de processos",
            },
        ),
        migrations.AlterModelOptions(
            name="tiporeuniao",
            options={
                "verbose_name": "Tipo de Reunião",
                "verbose_name_plural": "Tipos de Reuniões",
            },
        ),
        migrations.AlterModelOptions(
            name="unidade",
            options={
                "ordering": ["sigla"],
                "verbose_name": "Unidade",
                "verbose_name_plural": "Unidades",
            },
        ),
        migrations.AlterField(
            model_name="auditor",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="Email"
            ),
        ),
        migrations.AlterField(
            model_name="auditor",
            name="grupo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="auditores",
                # CORRIGIDO AQUI:
                to="processos.GrupoAuditor",
                verbose_name="Grupo de Auditores",
            ),
        ),
        migrations.AlterField(
            model_name="auditor",
            name="nome",
            field=models.CharField(max_length=100, verbose_name="Nome"),
        ),
        migrations.AlterField(
            model_name="auditor",
            name="telefone",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Telefone"
            ),
        ),
        migrations.AlterField(
            model_name="categoria",
            name="nome",
            field=models.CharField(max_length=100, verbose_name="Nome"),
        ),
        migrations.AlterField(
            model_name="categoria",
            name="valor",
            field=models.IntegerField(unique=True, verbose_name="Valor"),
        ),
        migrations.AlterField(
            model_name="reuniao",
            name="data",
            field=models.DateTimeField(verbose_name="Data"),
        ),
        migrations.RemoveField(
            model_name="reuniao",
            name="participantes",
        ),
        migrations.AlterField(
            model_name="reuniao",
            name="pauta",
            field=models.TextField(verbose_name="Pauta"),
        ),
        migrations.AlterField(
            model_name="reuniao",
            name="processo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reunioes",
                to="processos.processo",
                verbose_name="Processo",
            ),
        ),
        migrations.AlterField(
            model_name="reuniao",
            name="resultado",
            field=models.TextField(blank=True, null=True, verbose_name="Resultado"),
        ),
        migrations.AlterField(
            model_name="reuniao",
            name="tipo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="processos.tiporeuniao",
                verbose_name="Tipo",
            ),
        ),
        migrations.AlterField(
            model_name="unidade",
            name="descricao",
            field=models.TextField(blank=True, null=True, verbose_name="Descrição"),
        ),
        migrations.AlterField(
            model_name="unidade",
            name="nome",
            field=models.CharField(max_length=100, verbose_name="Nome"),
        ),
        migrations.AlterField(
            model_name="unidade",
            name="sigla",
            field=models.CharField(max_length=20, unique=True, verbose_name="Sigla"),
        ),
        migrations.AlterField(
            model_name="processo",
            name="atribuicao",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="processos_atribuidos",
                to="processos.atribuicao",
                verbose_name="Área de Atribuição",
            ),
        ),
        migrations.AddField(
            model_name="reuniao",
            name="participantes",
            field=models.TextField(
                blank=True,
                help_text="Liste os nomes dos participantes, um por linha ou separados por vírgula.",
                verbose_name="Participantes",
            ),
        ),
    ]
