# Generated by Django 5.2 on 2025-04-09 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("processos", "0002_atribuicao_rename_grupo_grupoauditor_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="unidade",
            name="descricao",
        ),
        migrations.AddField(
            model_name="unidade",
            name="codigo",
            field=models.CharField(
                default="000", max_length=10, unique=True, verbose_name="Codigo"
            ),
        ),
        migrations.AddField(
            model_name="unidade",
            name="uf",
            field=models.CharField(default=0, max_length=2, verbose_name="Nome"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="unidade",
            name="sigla",
            field=models.CharField(max_length=20, verbose_name="Sigla"),
        ),
    ]
