# Generated by Django 5.2 on 2025-04-09 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "processos",
            "0003_remove_unidade_descricao_unidade_codigo_unidade_uf_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="unidade",
            options={
                "ordering": ["nome"],
                "verbose_name": "Unidade",
                "verbose_name_plural": "Unidades",
            },
        ),
        migrations.RemoveField(
            model_name="unidade",
            name="codigo",
        ),
        migrations.RemoveField(
            model_name="unidade",
            name="sigla",
        ),
        migrations.RemoveField(
            model_name="unidade",
            name="uf",
        ),
        migrations.AlterField(
            model_name="unidade",
            name="nome",
            field=models.CharField(max_length=250, verbose_name="Nome"),
        ),
    ]
