# Generated by Django 5.2 on 2025-04-09 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("processos", "0004_alter_unidade_options_remove_unidade_codigo_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reuniao",
            options={
                "ordering": ["tipo"],
                "verbose_name": "Reunião",
                "verbose_name_plural": "Reuniões",
            },
        ),
        migrations.RemoveField(
            model_name="processo",
            name="unidade_auditada",
        ),
        migrations.AddField(
            model_name="processo",
            name="unidade_auditada",
            field=models.ManyToManyField(
                blank=True,
                related_name="processos",
                to="processos.unidade",
                verbose_name="Unidades Auditadas",
            ),
        ),
    ]
