# Generated by Django 5.2 on 2025-04-10 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("processos", "0005_alter_reuniao_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TipoDemanda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name": "Tipo de Demanda",
                "verbose_name_plural": "Tipos de Demandas",
            },
        ),
        migrations.CreateModel(
            name="Demanda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assunto", models.CharField(max_length=200, verbose_name="Assunto")),
                (
                    "situacao",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente de resposta"),
                            ("respondida", "Respondida"),
                            ("em_analise", "Em análise"),
                            ("concluida", "Concluída"),
                        ],
                        default="pendente",
                        max_length=20,
                        verbose_name="Situação",
                    ),
                ),
                (
                    "prioridade",
                    models.CharField(
                        choices=[
                            ("normal", "Normal"),
                            ("alta", "Alta"),
                            ("urgente", "Urgente"),
                        ],
                        default="normal",
                        max_length=10,
                        verbose_name="Prioridade",
                    ),
                ),
                (
                    "numero_processo_externo",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Número do Processo Externo",
                    ),
                ),
                (
                    "prazo_inicial",
                    models.DateField(
                        blank=True, null=True, verbose_name="Prazo Inicial"
                    ),
                ),
                (
                    "solicitacao_prorrogacao",
                    models.CharField(
                        choices=[("sim", "Sim"), ("nao", "Não")],
                        default="nao",
                        max_length=3,
                        verbose_name="Solicitação de Prorrogação",
                    ),
                ),
                (
                    "data_solicitacao_prorrogacao",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Data da Solicitação de Prorrogação",
                    ),
                ),
                (
                    "prazo_solicitado",
                    models.DateField(
                        blank=True, null=True, verbose_name="Prazo Solicitado"
                    ),
                ),
                (
                    "prazo_autorizado",
                    models.DateField(
                        blank=True, null=True, verbose_name="Prazo Autorizado"
                    ),
                ),
                (
                    "documento_resposta",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Documento de Resposta",
                    ),
                ),
                (
                    "data_resposta",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data da Resposta"
                    ),
                ),
                (
                    "numero_sei_resposta",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Número SEI da Resposta",
                    ),
                ),
                (
                    "data_envio_resposta",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data do Envio da Resposta"
                    ),
                ),
                (
                    "reiterado",
                    models.CharField(
                        choices=[("sim", "Sim"), ("nao", "Não")],
                        default="nao",
                        max_length=3,
                        verbose_name="Reiterado",
                    ),
                ),
                (
                    "data_reiteracao",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data da Reiteração"
                    ),
                ),
                (
                    "observacao",
                    models.TextField(
                        blank=True,
                        max_length=5000,
                        null=True,
                        verbose_name="Observação",
                    ),
                ),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "data_atualizacao",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
                (
                    "area_demandada",
                    models.ManyToManyField(
                        blank=True,
                        related_name="demandas",
                        to="processos.unidade",
                        verbose_name="Áreas Demandadas",
                    ),
                ),
                (
                    "atribuicao",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="demandas_atribuidas",
                        to="processos.atribuicao",
                        verbose_name="Área de Atribuição",
                    ),
                ),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="demandas",
                        to="processos.categoria",
                    ),
                ),
                (
                    "processo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="demandas",
                        to="processos.processo",
                    ),
                ),
                (
                    "tipo_demanda",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="demandas",
                        to="processos.tipodemanda",
                        verbose_name="Tipo de Demanda",
                    ),
                ),
            ],
            options={
                "verbose_name": "Demanda",
                "verbose_name_plural": "Demandas",
                "ordering": ["-data_criacao"],
            },
        ),
    ]
