# Generated by Django 5.2 on 2025-04-10 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("processos", "0006_tipodemanda_demanda"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="demanda",
            name="data_solicitacao_prorrogacao",
        ),
        migrations.RemoveField(
            model_name="demanda",
            name="prazo_autorizado",
        ),
        migrations.RemoveField(
            model_name="demanda",
            name="prazo_solicitado",
        ),
        migrations.RemoveField(
            model_name="demanda",
            name="solicitacao_prorrogacao",
        ),
        migrations.CreateModel(
            name="PedidoProrrogacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_solicitacao",
                    models.DateField(verbose_name="Data da Solicitação"),
                ),
                ("prazo_solicitado", models.DateField(verbose_name="Prazo Solicitado")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("solicitado", "Solicitado"),
                            ("aprovado", "Aprovado"),
                            ("reprovado", "Reprovado"),
                            ("parcial", "Aprovado Parcialmente"),
                        ],
                        default="solicitado",
                        max_length=10,
                        verbose_name="Status",
                    ),
                ),
                (
                    "prazo_autorizado",
                    models.DateField(
                        blank=True, null=True, verbose_name="Prazo Autorizado"
                    ),
                ),
                (
                    "demanda",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prorrogacoes",
                        to="processos.demanda",
                        verbose_name="Demanda",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pedido de Prorrogação",
                "verbose_name_plural": "Pedidos de Prorrogação",
                "ordering": ["-data_solicitacao"],
            },
        ),
    ]
