# Generated by Django 5.2 on 2025-04-10 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("processos", "0007_remove_demanda_data_solicitacao_prorrogacao_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pedidoprorrogacao",
            name="data_decisao",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data da Decisão"
            ),
        ),
    ]
