# Generated by Django 5.2 on 2025-04-09 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usuario",
            name="departamento",
        ),
        migrations.AddField(
            model_name="usuario",
            name="unidade",
            field=models.CharField(blank=True, max_length=100, verbose_name="Unidade"),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="email",
            field=models.EmailField(blank=True, max_length=254, verbose_name="E-mail"),
        ),
    ]
