# Generated by Django 5.2 on 2025-04-21 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="usuario",
            managers=[],
        ),
        migrations.AlterField(
            model_name="usuario",
            name="email",
            field=models.EmailField(max_length=254, unique=True, verbose_name="E-mail"),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="username",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="Username"
            ),
        ),
    ]
